config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/search", :to => 'pages#search', :as => :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'

  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
    resources :search, only: :create
    resources :reviews, only: :create
  end
  resources :users, only: :show
  post "favorite", to: "favorites#favorite"
  post "unfavorite", to: "favorites#unfavorite"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :place 

    validates :place_id, uniqueness: { scope: :place_id }
end

app/models/city.rb
class City < ApplicationRecord
    has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :comments, presence: true, length: { maximum: 140, minimum: 3 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :place 
    belongs_to :user

    validates :user_id, uniqueness: { scope: :place_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  #has_one :city
  has_many :comments
  has_many :images

  has_many :favorites, dependent: :destroy
  has_many :categories
  has_many :users, through: :favorites

  #has_many :favorites, dependent: :destroy
  has_many :categories
  #has_many :users, through: :favorites

  has_many :reviews
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :image, presence: true

  #validates :city, presence: true

  validates :phone_number, presence: true
  validates :website, presence: true
  validates :hours, presence: true
  #validates :city, presence: true



 
  def average_rating
    return 0 if self.reviews.count < 1

    sum = self.reviews.map(&:rating).reduce(:+)
    avg = sum / self.reviews.count.to_f
  end

  def average_rating_half_starred
    self.average_rating % 1 == 0 ? 0 : 1
  end

  def average_rating_unstarred
    5 - self.average_rating.floor - self.average_rating_half_starred
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place
  has_many :comments 

  RATINGS = {
     'one star': 1,
    'two stars': 2,
    'three stars': 3,
    'four stars': 4,
    'five stars': 5
  }

  def unstarred
    5-self.rating.to_i
  end
  
end

app/models/state.rb
class State < ApplicationRecord
    belongs_to :place
    
    state = Array[ 
            ["AK", "Alaska"], 
            ["AL", "Alabama"], 
            ["AR", "Arkansas"], 
            ["AS", "American Samoa"], 
            ["AZ", "Arizona"], 
            ["CA", "California"], 
            ["CO", "Colorado"], 
            ["CT", "Connecticut"], 
            ["DC", "District of Columbia"], 
            ["DE", "Delaware"], 
            ["FL", "Florida"], 
            ["GA", "Georgia"], 
            ["GU", "Guam"], 
            ["HI", "Hawaii"], 
            ["IA", "Iowa"], 
            ["ID", "Idaho"], 
            ["IL", "Illinois"], 
            ["IN", "Indiana"], 
            ["KS", "Kansas"], 
            ["KY", "Kentucky"], 
            ["LA", "Louisiana"], 
            ["MA", "Massachusetts"], 
            ["MD", "Maryland"], 
            ["ME", "Maine"], 
            ["MI", "Michigan"], 
            ["MN", "Minnesota"], 
            ["MO", "Missouri"], 
            ["MS", "Mississippi"], 
            ["MT", "Montana"], 
            ["NC", "North Carolina"], 
            ["ND", "North Dakota"], 
            ["NE", "Nebraska"], 
            ["NH", "New Hampshire"], 
            ["NJ", "New Jersey"], 
            ["NM", "New Mexico"], 
            ["NV", "Nevada"], 
            ["NY", "New York"], 
            ["OH", "Ohio"], 
            ["OK", "Oklahoma"], 
            ["OR", "Oregon"], 
            ["PA", "Pennsylvania"], 
            ["PR", "Puerto Rico"], 
            ["RI", "Rhode Island"], 
            ["SC", "South Carolina"], 
            ["SD", "South Dakota"], 
            ["TN", "Tennessee"], 
            ["TX", "Texas"], 
            ["UT", "Utah"], 
            ["VA", "Virginia"], 
            ["VI", "Virgin Islands"], 
            ["VT", "Vermont"], 
            ["WA", "Washington"], 
            ["WI", "Wisconsin"], 
            ["WV", "West Virginia"], 
            ["WY", "Wyoming"] 
                ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  has_many :places
  has_many :comments
  has_many :favorites, dependent: :destroy

  #has_many :places, through: :favorites


  has_many :reviews 
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end   

  def favorite!(place)
    favorites.create!(place_id: place.id)
  end

  def unfavorite!(favorite)
    favorites.find(favorite.id).destroy!
  end

  def favorite?(place)
    Favorite.where(place_id: place.id).where(user_id: self.id).count > 0
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index_favorites/_button.html.erb
<div id="<%= place.id %>">
    <% if current_user.favorite?(place) %>
        <%= button_to "Unfavorite", unfavorite_path(place_id: place.id), remote: true, method: :delete %>
    <% else %>
        <%= button_to "Favorite", favorite_path(place_id: place.id), remote: true %>
    <% end %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Nativ</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <nav class="navbar navbar-expand-md navbar-dark bg-danger">
    <%= link_to 'Nativ', root_path, class: 'navbar-brand navbar-logo' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar6">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-stretch" id="navbar6">
      <ul class="navbar-nav">
        <li class="nav-item active">
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-outline-light btn-sm navbar-btn' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-light btn-sm' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
  <%= render 'static_pages/footer' %>
</body>

</html>

app/views/pages/search.html.erb
<h3>Search Result</h3>  
    <% @results.each do |result| %>  
    <%= result.name %><br>  
    <% end %>