config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/search", :to => 'pages#search', :as => :search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'

  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
    resources :search, only: :create
    resources :reviews, only: :create
  end
  resources :users, only: :show
  post "favorite", to: "favorites#favorite"
  post "unfavorite", to: "favorites#unfavorite"
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  #has_one :city
  has_many :comments
  has_many :images

  has_many :favorites, dependent: :destroy
  has_many :categories
  has_many :users, through: :favorites

  #has_many :favorites, dependent: :destroy
  has_many :categories
  #has_many :users, through: :favorites

  has_many :reviews
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :image, presence: true

  #validates :city, presence: true

  validates :phone_number, presence: true
  validates :website, presence: true
  validates :hours, presence: true
  #validates :city, presence: true



 
  def average_rating
    return 0 if self.reviews.count < 1

    sum = self.reviews.map(&:rating).reduce(:+)
    avg = sum / self.reviews.count.to_f
  end

  def average_rating_half_starred
    self.average_rating % 1 == 0 ? 0 : 1
  end

  def average_rating_unstarred
    5 - self.average_rating.floor - self.average_rating_half_starred
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :favorite]
  
    def index
      @places = Place.all
    end
  
    def new
      @place = Place.new
    end
  
    def create
      @place = current_user.places.create(place_params)
      if @place.valid?
          flash[:success] = "Your place has been added!"
          redirect_to root_path
      else
          flash[:alert] = "Your new place couldn't be created!  Please check the form."
          render :new, status: :unprocessable_entity
      end
    end
  
    def show
      @comment = Comment.new
      @review  = Review.new
      @place = Place.find_by_id(params[:id])
      return render_not_found if @place.blank?

    end
  
    def edit
      @place = Place.find_by_id(params[:id])
      return render_not_found if @place.blank?
      return render_forbidden if @place.user != current_user
      if @place.user != current_user 
        return render plain: 'Not Allowed', status: :forbidden
      end
    end
  
    
    def update
      @place = Place.find_by_id(params[:id])
      return render_not_found if @place.blank?
      return render_forbidden if @place.user != current_user
      if @place.user != current_user
        return render plain: 'Not Allowed', status: :forbidden
      end
  
      @place.update_attributes(place_params)
      if @place.valid?
        flash[:success] = "Your place has been updated!"
        redirect_to root_path
      else
        flash[:alert] = "Your new place couldn't be updated!  Please check the form."
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @place = Place.find_by_id(params[:id])
      return render_not_found if @place.blank?
      return render_forbidden if @place.user != current_user
      if @place.user != current_user
        return render plain: 'Not Allowed', status: :forbidden
      end
  
      @place.destroy
      redirect_to root_path
    end

    # def favorite
    #  type = params[:type]
    #  if type == "favorite"
    #    current_user.favorites << @place 
    #    redirect_to places_path, notice: "You favorited #{@place.name}"
    #  elsif type == "unfavorite"
    #    current_user.favorites.delete(@place)
    #    redirect_to places_path, notice: "Unfavorited #{@place.name}"
    #  else
    #    redirect_to places_path, notice: "Nothing happend"
    #  end
    # end

  
    private
  
    def place_params
      params.require(:place).permit(:name, :description, :address, :phone_number, :image, :website, :hours)
    end

    def render_not_found
    render plain: 'Not Found :(', status: :not_found
    end

    def render_forbidden
    render plain: 'Forbidden', status: :forbidden
    end

  end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<h1>Edit Your Nativ Hotspot!</h1>
<br />
<br />
<div class="booyah-box col-10 offset-1">
    <%= simple_form_for @place do |f| %>
    <br />
    <br />
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :website %>
    <%= f.input :hours %>
    <br />
    <%= f.label :catergory_id, as: :check_boxes %>
    <br /><br />
    <%= f.input :image %><br /><br>
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
  </div>

app/views/places/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
<script src="//geodata.solutions/includes/statecity.js"></script>
<script src="/jQuery/dist/jquery.js"></script>
<script src="/javascripts/main.js"></script>

<!DOCTYPE html>	
<html>

<head>
<script>
 $(document).ready(function() {
      $('#stateId').click(function(data) { 
          console.log(data)
        });
        });
      $('#cityId').click(function(data) { 
          console.log(data)
    }); 
</script>
</head>



<body>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <!-- <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> -->
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'louis-hansel-Zkgs86--KIo-unsplash.jpg', class: 'd-block img-fluid' %>     
    </div>
    <div class="carousel-item">
      <%= image_tag 'rod-long-I79Pgmhmy5M-unsplash.jpg', class: 'd-block img-fluid' %>     
    </div>
    <div class="carousel-item">
      <%= image_tag 'jonathan-nguyen-XwO0raJ2dQM-unsplash.jpg', class: 'd-block img-fluid' %>     
    </div>
    <div class="carousel-item">
      <%= image_tag 'rahul-jain-egKF-_SmP2M-unsplash.jpg', class: 'd-block img-fluid' %>     
    </div>
    <div class="carousel-item">
      <%= image_tag 'johnny-martinez-lBIFDzYwbDo-unsplash.jpg', class: 'd-block img-fluid' %>     
    </div>
    <div class="carousel-item">
      <%= image_tag 'zach-lucero-Cwf7wiha5oY-unsplash.jpg', class: 'd-block img-fluid' %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<section class="search-sec">
  <div class="container">
    <form action="/search" method="gets" novalidate="novalidate">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
              <input type="hidden" name="country" id="countryId" value="US"/>
                <select name="state" class="states order-alpha, form-control search-slt" id="stateId">
                  <option value="">Select State</option>
                </select>
              </div>
            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
              <select name="city" class="cities order-alpha, form-control search-slt" id="cityId">
                <option value="">Select City</option>
                <%= form_tag(search_path, :method => "get") do %>
              </select>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
              <select class="form-control search-slt" id="exampleFormControlSelect1">
                <option>Cuisine</option>
                <option>Chinese</option>
                <option>Indian</option>
                <option>Thai</option>
                <option>American</option>
              </select>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
              <%= button_tag "Search", :class => "btn btn-danger wrn-btn", :name => nil%>
            </div>
            <div class="dd-title col-10 offset-3">                  
              <ul id="match_location"></ul>
            </div>
            <div class="drop-down col-10 offset-4">
              <!-- Removed due to jQuery download links! -->
            </div>
            <%end%>
          </div>
       </div>
      </div>
    </form>
  </div>
</section>


<% @places.each do |place| %>
<div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <% if place.image.url.present? %>
      <%=image_tag place.image.url, class: "img-thumbnail"%>
    <% end %>
    <br /><br />
    <%= link_to 'More', place_path(place), class: 'btn btn-primary' %><br /><br />
    <div class="address">
    <span class="fas fa-map-marker-alt"></span> &nbsp;
      <%= place.address %>
    </div><br/>
    <div class="address">
    <span class="fas fa-phone"></span>&nbsp;
      <%= place.phone_number %>
    </div><br />
    <div class="address">
    <span class="fas fa-clock"></span>&nbsp;
      <%= place.hours %>
    </div><br />
    <div class="address">
    <span class="fas fa-link"></span>&nbsp;
    <a href="<%= place.website %>"> <%= place.website %></a>
    </div><br />
    <br />
    <p><%= place.description %></p><br />
    <br />
      <% if current_user %>
        <div id=<%= place.id %>>
          <%= render partial: "favorites/button", locals: {place: place} %>
        </div>
      <% end %>

  <% if place.comments.present? %>
  <h2> Reviews & Ratings </h2><br/>
        <div class="col-12 col-sm-6">
          <blockquote>
          <%= place.comments.last.message %>
          <!-- <small><%= place.comments.last.user.email %></small>  -->
          </blockquote>
        </div>
      <% end %>
    </div>
  <% end %>
<br />

</body>

app/views/places/new.html.erb
<br />
<h1> Add a Nativ hotspot!</h1>
<br />
<br />
<div class="booyah-box col-10 offset-1">
    <%= simple_form_for @place do |f| %>
    <br />
    <br />
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :website %>
    <%= f.input :hours %>
    <br />
    <%= f.label :catergory_id, as: :check_boxes %>
    <br /><br />
    <%= f.input :image %><br /><br>
    <%= f.submit 'Submit', class: 'btn btn-dark' %>
  <% end %>
  </div>

app/views/places/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<div class="booyah-box col-10 offset-1"><br />
  <h1><%= @place.name %></h1><br />
    <% if current_user %>
      <div id="<%= @place.id %>" class="favorite-button">
        <%= render partial: "favorites/button", locals: {place: @place} %>
      </div>
    <% end %>
  <% if @place.image.url.present? %>
    <%=image_tag @place.image.url, class: "img-thumbnail"%>
  <% end %> <br /><br />
  <div class="address">
    <span class="fas fa-map-marker-alt"></span> &nbsp;
  <%= @place.address %>
  </div><br />
  <div class="address">
    <span class="fas fa-phone"></span>&nbsp;
  <%= @place.phone_number %>
  </div><br />
  <div class="address">
    <span class="fas fa-link"></span>&nbsp;
  <a href="<%= @place.website %>"> <%= @place.website %></a>
  </div><br />
  <div class="address">
    <span class="fas fa-clock"></span>&nbsp;
      <%= @place.hours %>
    </div><br />
  <p><%= @place.description %></p>
  
  <b><% @place.average_rating.floor.times do  %></b>
    <i class="fa fa-star"></i>
  <%end %>
  <b><% @place.average_rating_half_starred.times do %></b>
    <i class="fa fa-star-half-o"></i>
  <% end %>
  <b><% @place.average_rating_unstarred.times do %></b>
    <i class="fa fa-star-o"></i>
  <% end %><br /><br />

<!-- MAP CODE -->
<style>
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    #map {
      height: 300px;
    }
   
  </style>

  <% if @place.latitude.present? && @place.longitude.present? %>

  <script>

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

   <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvOsQTnJ8_OAx6sYCr1FSo9M7SyS76ETU&callback=initMap">
  </script>

<div id="map"></div>
<% end %>

<br />

  <div class="float-right">
    <% if current_user && current_user == @place.user %>
    <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-dark' %>
    <%= link_to 'Delete', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this place?'}, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

<div class="clear"></div>

<!-- Reviews Modal -->
<div class="modal fade" id="reviewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
          <h4 class="modal-title" id="myModalLabel">Write a review</h4>
      </div>
      <%= simple_form_for @review, url: place_reviews_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :rating, as: :select, collection: Review::RATINGS %>
          <br/>
          <%= f.input :message %>
        </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          <%= f.submit "Write a Review", class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>
<br/>
<br/>

<div class="clear"></div>

<div class="col-10 offset-1">
<h1 class="float-left">Reviews</h1>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#reviewModal">
  Write a Review
</button>
</div>
<div class="clear"></div>
<div class="row">
<% @place.reviews.each do |review| %>
  <div class="booyah-box col-12 col-sm-8 offset-2">
    <blockquote>
      <% if review.rating.present? %> 
                <b><% review.rating.times do  %></b>
                <i class="fa fa-star"></i>
                <%end %>
                <b><% review.unstarred.times do %></b>
                <i class="fa fa-star-o"></i>
                <% end %>
      <% end %>
          -
          <%= review.message %>
          
    </blockquote>
  </div>
<% end %>
</div>


<!-- Comments Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
        </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>
<br/>
<br/>

<div class="clear"></div>

<div class="col-10 offset-1">
<h1 class="float-left">Comments</h1>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
  Add a comment
</button>
</div>
<div class="clear"></div>
<div class="row">
<% @place.comments.each do |comment| %>
  <div class="booyah-box col-12 col-sm-8 offset-2">
    <blockquote>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>
</div>